/**
 * Disables HTMLMotionProps noise in Storybook Controls.
 * Spread into `argTypes` for any component that extends motion/react props.
 */
export const EXCLUDE_MOTION_PROPS = {
  initial:              { table: { disable: true } },
  animate:              { table: { disable: true } },
  exit:                 { table: { disable: true } },
  variants:             { table: { disable: true } },
  transition:           { table: { disable: true } },
  whileHover:           { table: { disable: true } },
  whileTap:             { table: { disable: true } },
  whileFocus:           { table: { disable: true } },
  whileDrag:            { table: { disable: true } },
  whileInView:          { table: { disable: true } },
  drag:                 { table: { disable: true } },
  dragConstraints:      { table: { disable: true } },
  dragControls:         { table: { disable: true } },
  dragElastic:          { table: { disable: true } },
  dragMomentum:         { table: { disable: true } },
  dragPropagation:      { table: { disable: true } },
  dragSnapToOrigin:     { table: { disable: true } },
  dragTransition:       { table: { disable: true } },
  layout:               { table: { disable: true } },
  layoutId:             { table: { disable: true } },
  layoutDependency:     { table: { disable: true } },
  layoutScroll:         { table: { disable: true } },
  onAnimationStart:     { table: { disable: true } },
  onAnimationComplete:  { table: { disable: true } },
  onDrag:               { table: { disable: true } },
  onDragStart:          { table: { disable: true } },
  onDragEnd:            { table: { disable: true } },
  onHoverStart:         { table: { disable: true } },
  onHoverEnd:           { table: { disable: true } },
  onTap:                { table: { disable: true } },
  onTapStart:           { table: { disable: true } },
  onTapCancel:          { table: { disable: true } },
  onViewportEnter:      { table: { disable: true } },
  onViewportLeave:      { table: { disable: true } },
  style:                { table: { disable: true } },
  transformTemplate:    { table: { disable: true } },
} as const;
