// Generated by scripts/generate-tokens.mjs — do not edit by hand

export type ColorToken = {
  name: string;
  cssVar: string;
  scale?: string;
  description?: string;
};

export type ColorPrimitiveToken = ColorToken & { scale: string };

export const colorPrimitives: ColorPrimitiveToken[] = [
  { name: 'orbit-blue-25', cssVar: '--orbit-blue-25', scale: 'Orbit Blue' },
  { name: 'orbit-blue-50', cssVar: '--orbit-blue-50', scale: 'Orbit Blue' },
  { name: 'orbit-blue-100', cssVar: '--orbit-blue-100', scale: 'Orbit Blue' },
  { name: 'orbit-blue-200', cssVar: '--orbit-blue-200', scale: 'Orbit Blue' },
  { name: 'orbit-blue-300', cssVar: '--orbit-blue-300', scale: 'Orbit Blue' },
  { name: 'orbit-blue-400', cssVar: '--orbit-blue-400', scale: 'Orbit Blue' },
  { name: 'orbit-blue-500', cssVar: '--orbit-blue-500', scale: 'Orbit Blue' },
  { name: 'orbit-blue-600', cssVar: '--orbit-blue-600', scale: 'Orbit Blue' },
  { name: 'orbit-blue-700', cssVar: '--orbit-blue-700', scale: 'Orbit Blue' },
  { name: 'orbit-blue-800', cssVar: '--orbit-blue-800', scale: 'Orbit Blue' },
  { name: 'orbit-blue-900', cssVar: '--orbit-blue-900', scale: 'Orbit Blue' },
  { name: 'orbit-blue-950', cssVar: '--orbit-blue-950', scale: 'Orbit Blue' },
  { name: 'cosmic-lilac-25', cssVar: '--cosmic-lilac-25', scale: 'Cosmic Lilac' },
  { name: 'cosmic-lilac-50', cssVar: '--cosmic-lilac-50', scale: 'Cosmic Lilac' },
  { name: 'cosmic-lilac-100', cssVar: '--cosmic-lilac-100', scale: 'Cosmic Lilac' },
  { name: 'cosmic-lilac-200', cssVar: '--cosmic-lilac-200', scale: 'Cosmic Lilac' },
  { name: 'cosmic-lilac-300', cssVar: '--cosmic-lilac-300', scale: 'Cosmic Lilac' },
  { name: 'cosmic-lilac-400', cssVar: '--cosmic-lilac-400', scale: 'Cosmic Lilac' },
  { name: 'cosmic-lilac-500', cssVar: '--cosmic-lilac-500', scale: 'Cosmic Lilac' },
  { name: 'cosmic-lilac-600', cssVar: '--cosmic-lilac-600', scale: 'Cosmic Lilac' },
  { name: 'cosmic-lilac-700', cssVar: '--cosmic-lilac-700', scale: 'Cosmic Lilac' },
  { name: 'cosmic-lilac-800', cssVar: '--cosmic-lilac-800', scale: 'Cosmic Lilac' },
  { name: 'cosmic-lilac-900', cssVar: '--cosmic-lilac-900', scale: 'Cosmic Lilac' },
  { name: 'cosmic-lilac-950', cssVar: '--cosmic-lilac-950', scale: 'Cosmic Lilac' },
  { name: 'lumen-yellow-25', cssVar: '--lumen-yellow-25', scale: 'Lumen Yellow' },
  { name: 'lumen-yellow-50', cssVar: '--lumen-yellow-50', scale: 'Lumen Yellow' },
  { name: 'lumen-yellow-100', cssVar: '--lumen-yellow-100', scale: 'Lumen Yellow' },
  { name: 'lumen-yellow-200', cssVar: '--lumen-yellow-200', scale: 'Lumen Yellow' },
  { name: 'lumen-yellow-300', cssVar: '--lumen-yellow-300', scale: 'Lumen Yellow' },
  { name: 'lumen-yellow-400', cssVar: '--lumen-yellow-400', scale: 'Lumen Yellow' },
  { name: 'lumen-yellow-500', cssVar: '--lumen-yellow-500', scale: 'Lumen Yellow' },
  { name: 'lumen-yellow-600', cssVar: '--lumen-yellow-600', scale: 'Lumen Yellow' },
  { name: 'lumen-yellow-700', cssVar: '--lumen-yellow-700', scale: 'Lumen Yellow' },
  { name: 'lumen-yellow-800', cssVar: '--lumen-yellow-800', scale: 'Lumen Yellow' },
  { name: 'lumen-yellow-900', cssVar: '--lumen-yellow-900', scale: 'Lumen Yellow' },
  { name: 'lumen-yellow-950', cssVar: '--lumen-yellow-950', scale: 'Lumen Yellow' },
  { name: 'nova-mint-25', cssVar: '--nova-mint-25', scale: 'Nova Mint' },
  { name: 'nova-mint-50', cssVar: '--nova-mint-50', scale: 'Nova Mint' },
  { name: 'nova-mint-100', cssVar: '--nova-mint-100', scale: 'Nova Mint' },
  { name: 'nova-mint-200', cssVar: '--nova-mint-200', scale: 'Nova Mint' },
  { name: 'nova-mint-300', cssVar: '--nova-mint-300', scale: 'Nova Mint' },
  { name: 'nova-mint-400', cssVar: '--nova-mint-400', scale: 'Nova Mint' },
  { name: 'nova-mint-500', cssVar: '--nova-mint-500', scale: 'Nova Mint' },
  { name: 'nova-mint-600', cssVar: '--nova-mint-600', scale: 'Nova Mint' },
  { name: 'nova-mint-700', cssVar: '--nova-mint-700', scale: 'Nova Mint' },
  { name: 'nova-mint-800', cssVar: '--nova-mint-800', scale: 'Nova Mint' },
  { name: 'nova-mint-900', cssVar: '--nova-mint-900', scale: 'Nova Mint' },
  { name: 'nova-mint-950', cssVar: '--nova-mint-950', scale: 'Nova Mint' },
  { name: 'solar-coral-25', cssVar: '--solar-coral-25', scale: 'Solar Coral' },
  { name: 'solar-coral-50', cssVar: '--solar-coral-50', scale: 'Solar Coral' },
  { name: 'solar-coral-100', cssVar: '--solar-coral-100', scale: 'Solar Coral' },
  { name: 'solar-coral-200', cssVar: '--solar-coral-200', scale: 'Solar Coral' },
  { name: 'solar-coral-300', cssVar: '--solar-coral-300', scale: 'Solar Coral' },
  { name: 'solar-coral-400', cssVar: '--solar-coral-400', scale: 'Solar Coral' },
  { name: 'solar-coral-500', cssVar: '--solar-coral-500', scale: 'Solar Coral' },
  { name: 'solar-coral-600', cssVar: '--solar-coral-600', scale: 'Solar Coral' },
  { name: 'solar-coral-700', cssVar: '--solar-coral-700', scale: 'Solar Coral' },
  { name: 'solar-coral-800', cssVar: '--solar-coral-800', scale: 'Solar Coral' },
  { name: 'solar-coral-900', cssVar: '--solar-coral-900', scale: 'Solar Coral' },
  { name: 'solar-coral-950', cssVar: '--solar-coral-950', scale: 'Solar Coral' },
  { name: 'space-white-25', cssVar: '--space-white-25', scale: 'Space White' },
  { name: 'space-white-50', cssVar: '--space-white-50', scale: 'Space White' },
  { name: 'space-white-100', cssVar: '--space-white-100', scale: 'Space White' },
  { name: 'space-white-200', cssVar: '--space-white-200', scale: 'Space White' },
  { name: 'space-white-300', cssVar: '--space-white-300', scale: 'Space White' },
  { name: 'space-white-400', cssVar: '--space-white-400', scale: 'Space White' },
  { name: 'space-white-500', cssVar: '--space-white-500', scale: 'Space White' },
  { name: 'space-white-600', cssVar: '--space-white-600', scale: 'Space White' },
  { name: 'space-white-700', cssVar: '--space-white-700', scale: 'Space White' },
  { name: 'space-white-800', cssVar: '--space-white-800', scale: 'Space White' },
  { name: 'space-white-900', cssVar: '--space-white-900', scale: 'Space White' },
  { name: 'space-white-950', cssVar: '--space-white-950', scale: 'Space White' },
  { name: 'white', cssVar: '--white', scale: 'Neutral' },
  { name: 'black', cssVar: '--black', scale: 'Neutral' },
];

export type SemanticColorGroup = {
  group: string;
  tokens: ColorToken[];
};


export const colorSemantic: SemanticColorGroup[] = [
  {
    group: 'Text',
    tokens: [
    { name: 'text-primary', cssVar: '--text-primary', description: 'text / primary' },
    { name: 'text-secondary', cssVar: '--text-secondary', description: 'text / secondary' },
    { name: 'text-tertiary', cssVar: '--text-tertiary', description: 'text / tertiary' },
    { name: 'text-placeholder', cssVar: '--text-placeholder', description: 'text / placeholder' },
    { name: 'text-inverse', cssVar: '--text-inverse', description: 'text / inverse' },
    ],
  },
  {
    group: 'Text / Interactive',
    tokens: [
    { name: 'text-interactive-primary', cssVar: '--text-interactive-primary', description: 'text / interactive / primary' },
    { name: 'text-interactive-secondary', cssVar: '--text-interactive-secondary', description: 'text / interactive / secondary' },
    { name: 'text-interactive-disabled', cssVar: '--text-interactive-disabled', description: 'text / interactive / disabled' },
    { name: 'text-interactive-error', cssVar: '--text-interactive-error', description: 'text / interactive / error (new 2026-08-11)' },
    { name: 'text-interactive-success', cssVar: '--text-interactive-success', description: 'text / interactive / success (new 2026-08-11)' },
    ],
  },
  {
    group: 'Text / Status',
    tokens: [
    { name: 'text-status-success', cssVar: '--text-status-success', description: 'text / status / success' },
    { name: 'text-status-warning', cssVar: '--text-status-warning', description: 'text / status / warning' },
    { name: 'text-status-error', cssVar: '--text-status-error', description: 'text / status / error' },
    { name: 'text-status-info', cssVar: '--text-status-info', description: 'text / status / info' },
    { name: 'text-status-info-secondary', cssVar: '--text-status-info-secondary', description: 'text / status / info-secondary (new 2026-08-11)' },
    ],
  },
  {
    group: 'Overlay',
    tokens: [
    { name: 'overlay-light', cssVar: '--overlay-light', description: 'overlay / light' },
    { name: 'overlay-medium', cssVar: '--overlay-medium', description: 'overlay / medium' },
    { name: 'overlay-heavy', cssVar: '--overlay-heavy', description: 'overlay / heavy' },
    ],
  },
  {
    group: 'Border',
    tokens: [
    { name: 'border-default', cssVar: '--border-default', description: 'border / default' },
    { name: 'border-subtle', cssVar: '--border-subtle', description: 'border / subtle' },
    { name: 'border-brand-default', cssVar: '--border-brand-default', description: 'border / brand / default' },
    { name: 'border-brand-subtle', cssVar: '--border-brand-subtle', description: 'border / brand / subtle' },
    { name: 'border-success', cssVar: '--border-success', description: 'border / success' },
    { name: 'border-error', cssVar: '--border-error', description: 'border / error' },
    { name: 'border-warning', cssVar: '--border-warning', description: 'border / warning' },
    { name: 'border-info', cssVar: '--border-info', description: 'border / info' },
    ],
  },
  {
    group: 'Background / Status',
    tokens: [
    { name: 'bg-status-success', cssVar: '--bg-status-success', description: 'bg / status / subtle / success' },
    { name: 'bg-status-warning', cssVar: '--bg-status-warning', description: 'bg / status / subtle / warning' },
    { name: 'bg-status-error', cssVar: '--bg-status-error', description: 'bg / status / subtle / error' },
    { name: 'bg-status-info', cssVar: '--bg-status-info', description: 'bg / status / subtle / info' },
    { name: 'bg-status-neutral', cssVar: '--bg-status-neutral', description: 'bg / status / subtle / neutral' },
    ],
  },
  {
    group: 'Background / Status / Default',
    tokens: [
    { name: 'bg-status-default-success', cssVar: '--bg-status-default-success', description: 'bg / status / default / success (new 2026-08-11)' },
    { name: 'bg-status-default-warning', cssVar: '--bg-status-default-warning', description: 'bg / status / default / warning (new 2026-08-11)' },
    { name: 'bg-status-default-error', cssVar: '--bg-status-default-error', description: 'bg / status / default / error (new 2026-08-11)' },
    { name: 'bg-status-default-info', cssVar: '--bg-status-default-info', description: 'bg / status / default / info (new 2026-08-11)' },
    { name: 'bg-status-default-neutral', cssVar: '--bg-status-default-neutral', description: 'bg / status / default / neutral (new 2026-08-11)' },
    ],
  },
  {
    group: 'Background / Surface',
    tokens: [
    { name: 'bg-surface-primary', cssVar: '--bg-surface-primary', description: 'bg / surface / primary' },
    { name: 'bg-surface-secondary', cssVar: '--bg-surface-secondary', description: 'bg / surface / secondary' },
    { name: 'bg-surface-tertiary', cssVar: '--bg-surface-tertiary', description: 'bg / surface / tertiary' },
    { name: 'bg-surface-subtle', cssVar: '--bg-surface-subtle', description: 'bg / surface / subtle (new 2026-08-11)' },
    { name: 'bg-surface-base', cssVar: '--bg-surface-base', description: 'bg / surface / base' },
    ],
  },
  {
    group: 'Background / Interactive / Primary',
    tokens: [
    { name: 'bg-interactive-primary-default', cssVar: '--bg-interactive-primary-default', description: 'bg / interactive / primary / default' },
    { name: 'bg-interactive-primary-hover', cssVar: '--bg-interactive-primary-hover', description: 'bg / interactive / primary / hover' },
    { name: 'bg-interactive-primary-pressed', cssVar: '--bg-interactive-primary-pressed', description: 'bg / interactive / primary / pressed' },
    { name: 'bg-interactive-primary-disabled', cssVar: '--bg-interactive-primary-disabled', description: 'bg / interactive / primary / disabled' },
    ],
  },
  {
    group: 'Background / Interactive / Primary Subtle',
    tokens: [
    { name: 'bg-interactive-primary-subtle-default', cssVar: '--bg-interactive-primary-subtle-default', description: 'bg / interactive / primary-subtle / default (new 2026-08-11)' },
    { name: 'bg-interactive-primary-subtle-hover', cssVar: '--bg-interactive-primary-subtle-hover', description: 'bg / interactive / primary-subtle / hover (new 2026-08-11)' },
    { name: 'bg-interactive-primary-subtle-pressed', cssVar: '--bg-interactive-primary-subtle-pressed', description: 'bg / interactive / primary-subtle / pressed (new 2026-08-11)' },
    { name: 'bg-interactive-primary-subtle-disabled', cssVar: '--bg-interactive-primary-subtle-disabled', description: 'bg / interactive / primary-subtle / disabled (new 2026-08-11)' },
    ],
  },
  {
    group: 'Border / Input',
    tokens: [
    { name: 'border-input-default', cssVar: '--border-input-default', description: 'border / input / default' },
    { name: 'border-input-focus', cssVar: '--border-input-focus', description: 'border / input / focus' },
    ],
  },
  {
    group: 'Background / Input',
    tokens: [
    { name: 'bg-input-default', cssVar: '--bg-input-default', description: 'bg / input / default' },
    ],
  },
  {
    group: 'Background / Interactive / Secondary',
    tokens: [
    { name: 'bg-interactive-secondary-default', cssVar: '--bg-interactive-secondary-default', description: 'bg / interactive / secondary / default' },
    { name: 'bg-interactive-secondary-hover', cssVar: '--bg-interactive-secondary-hover', description: 'bg / interactive / secondary / hover' },
    { name: 'bg-interactive-secondary-pressed', cssVar: '--bg-interactive-secondary-pressed', description: 'bg / interactive / secondary / pressed' },
    { name: 'bg-interactive-secondary-disabled', cssVar: '--bg-interactive-secondary-disabled', description: 'bg / interactive / secondary / disabled' },
    ],
  },
  {
    group: 'Background / Interactive / Secondary Ghost',
    tokens: [
    { name: 'bg-interactive-secondary-ghost-default', cssVar: '--bg-interactive-secondary-ghost-default', description: 'bg / interactive / secondary-ghost / default (new 2026-08-11)' },
    { name: 'bg-interactive-secondary-ghost-hover', cssVar: '--bg-interactive-secondary-ghost-hover', description: 'bg / interactive / secondary-ghost / hover (new 2026-08-11)' },
    { name: 'bg-interactive-secondary-ghost-pressed', cssVar: '--bg-interactive-secondary-ghost-pressed', description: 'bg / interactive / secondary-ghost / pressed (new 2026-08-11)' },
    { name: 'bg-interactive-secondary-ghost-disabled', cssVar: '--bg-interactive-secondary-ghost-disabled', description: 'bg / interactive / secondary-ghost / disabled (new 2026-08-11)' },
    ],
  },
  {
    group: 'Background / Interactive / Success',
    tokens: [
    { name: 'bg-interactive-success-default', cssVar: '--bg-interactive-success-default', description: 'bg / interactive / success / default' },
    { name: 'bg-interactive-success-hover', cssVar: '--bg-interactive-success-hover', description: 'bg / interactive / success / hover' },
    { name: 'bg-interactive-success-pressed', cssVar: '--bg-interactive-success-pressed', description: 'bg / interactive / success / pressed' },
    { name: 'bg-interactive-success-disabled', cssVar: '--bg-interactive-success-disabled', description: 'bg / interactive / success / disabled' },
    ],
  },
  {
    group: 'Background / Interactive / Success Subtle',
    tokens: [
    { name: 'bg-interactive-success-subtle-default', cssVar: '--bg-interactive-success-subtle-default', description: 'bg / interactive / success-subtle / default (new 2026-08-11)' },
    { name: 'bg-interactive-success-subtle-hover', cssVar: '--bg-interactive-success-subtle-hover', description: 'bg / interactive / success-subtle / hover (new 2026-08-11)' },
    { name: 'bg-interactive-success-subtle-pressed', cssVar: '--bg-interactive-success-subtle-pressed', description: 'bg / interactive / success-subtle / pressed (new 2026-08-11)' },
    { name: 'bg-interactive-success-subtle-disabled', cssVar: '--bg-interactive-success-subtle-disabled', description: 'bg / interactive / success-subtle / disabled (new 2026-08-11)' },
    ],
  },
  {
    group: 'Background / Interactive / Error',
    tokens: [
    { name: 'bg-interactive-error-default', cssVar: '--bg-interactive-error-default', description: 'bg / interactive / error / default' },
    { name: 'bg-interactive-error-hover', cssVar: '--bg-interactive-error-hover', description: 'bg / interactive / error / hover' },
    { name: 'bg-interactive-error-pressed', cssVar: '--bg-interactive-error-pressed', description: 'bg / interactive / error / pressed' },
    { name: 'bg-interactive-error-disabled', cssVar: '--bg-interactive-error-disabled', description: 'bg / interactive / error / disabled' },
    ],
  },
  {
    group: 'Background / Interactive / Error Subtle',
    tokens: [
    { name: 'bg-interactive-error-subtle-default', cssVar: '--bg-interactive-error-subtle-default', description: 'bg / interactive / error-subtle / default (new 2026-08-11)' },
    { name: 'bg-interactive-error-subtle-hover', cssVar: '--bg-interactive-error-subtle-hover', description: 'bg / interactive / error-subtle / hover (new 2026-08-11)' },
    { name: 'bg-interactive-error-subtle-pressed', cssVar: '--bg-interactive-error-subtle-pressed', description: 'bg / interactive / error-subtle / pressed (new 2026-08-11)' },
    { name: 'bg-interactive-error-subtle-disabled', cssVar: '--bg-interactive-error-subtle-disabled', description: 'bg / interactive / error-subtle / disabled (new 2026-08-11)' },
    ],
  },
  {
    group: 'Background / Brand Surface',
    tokens: [
    { name: 'bg-surface-brand-primary', cssVar: '--bg-surface-brand-primary', description: 'bg / surface-brand / primary' },
    { name: 'bg-surface-brand-secondary', cssVar: '--bg-surface-brand-secondary', description: 'bg / surface-brand / secondary' },
    { name: 'bg-surface-brand-tertiary', cssVar: '--bg-surface-brand-tertiary', description: 'bg / surface-brand / tertiary' },
    { name: 'bg-surface-brand-subtle', cssVar: '--bg-surface-brand-subtle', description: 'bg / surface-brand / subtle (new 2026-08-11)' },
    { name: 'bg-surface-brand-base', cssVar: '--bg-surface-brand-base', description: 'bg / surface-brand / base' },
    ],
  },
  {
    group: 'Background / Success Surface',
    tokens: [
    { name: 'bg-surface-success-primary', cssVar: '--bg-surface-success-primary', description: 'bg / surface-success / primary' },
    { name: 'bg-surface-success-secondary', cssVar: '--bg-surface-success-secondary', description: 'bg / surface-success / secondary' },
    { name: 'bg-surface-success-tertiary', cssVar: '--bg-surface-success-tertiary', description: 'bg / surface-success / tertiary' },
    { name: 'bg-surface-success-base', cssVar: '--bg-surface-success-base', description: 'bg / surface-success / base' },
    ],
  },
  {
    group: 'Background / Error Surface',
    tokens: [
    { name: 'bg-surface-error-primary', cssVar: '--bg-surface-error-primary', description: 'bg / surface-error / primary' },
    { name: 'bg-surface-error-secondary', cssVar: '--bg-surface-error-secondary', description: 'bg / surface-error / secondary' },
    { name: 'bg-surface-error-tertiary', cssVar: '--bg-surface-error-tertiary', description: 'bg / surface-error / tertiary' },
    { name: 'bg-surface-error-base', cssVar: '--bg-surface-error-base', description: 'bg / surface-error / base' },
    ],
  },
  {
    group: 'Background / Warning Surface',
    tokens: [
    { name: 'bg-surface-warning-primary', cssVar: '--bg-surface-warning-primary', description: 'bg / surface-warning / primary' },
    { name: 'bg-surface-warning-secondary', cssVar: '--bg-surface-warning-secondary', description: 'bg / surface-warning / secondary' },
    { name: 'bg-surface-warning-tertiary', cssVar: '--bg-surface-warning-tertiary', description: 'bg / surface-warning / tertiary' },
    { name: 'bg-surface-warning-base', cssVar: '--bg-surface-warning-base', description: 'bg / surface-warning / base' },
    ],
  },
  {
    group: 'Background / Interactive / Warning',
    tokens: [
    { name: 'bg-interactive-warning-default', cssVar: '--bg-interactive-warning-default', description: 'bg / interactive / warning / default' },
    { name: 'bg-interactive-warning-hover', cssVar: '--bg-interactive-warning-hover', description: 'bg / interactive / warning / hover' },
    { name: 'bg-interactive-warning-pressed', cssVar: '--bg-interactive-warning-pressed', description: 'bg / interactive / warning / pressed' },
    { name: 'bg-interactive-warning-disabled', cssVar: '--bg-interactive-warning-disabled', description: 'bg / interactive / warning / disabled' },
    ],
  },
  {
    group: 'Background / Interactive / Warning Subtle',
    tokens: [
    { name: 'bg-interactive-warning-subtle-default', cssVar: '--bg-interactive-warning-subtle-default', description: 'bg / interactive / warning-subtle / default (new 2026-08-11)' },
    { name: 'bg-interactive-warning-subtle-hover', cssVar: '--bg-interactive-warning-subtle-hover', description: 'bg / interactive / warning-subtle / hover (new 2026-08-11)' },
    { name: 'bg-interactive-warning-subtle-pressed', cssVar: '--bg-interactive-warning-subtle-pressed', description: 'bg / interactive / warning-subtle / pressed (new 2026-08-11)' },
    { name: 'bg-interactive-warning-subtle-disabled', cssVar: '--bg-interactive-warning-subtle-disabled', description: 'bg / interactive / warning-subtle / disabled (new 2026-08-11)' },
    ],
  },
];
