// Generated by scripts/generate-tokens.mjs — do not edit by hand

export type SpacingToken = {
  name: string;
  cssVar: string;
  remValue: string;
  pxValue: string;
};

export const spacingTokens: SpacingToken[] = [
  { name: 'spacing-0', cssVar: '--spacing-0', remValue: '0', pxValue: '0px' },
  { name: 'spacing-6xs', cssVar: '--spacing-6xs', remValue: '0.125rem', pxValue: '2px' },
  { name: 'spacing-5xs', cssVar: '--spacing-5xs', remValue: '0.25rem', pxValue: '4px' },
  { name: 'spacing-4xs', cssVar: '--spacing-4xs', remValue: '0.5rem', pxValue: '8px' },
  { name: 'spacing-3xs', cssVar: '--spacing-3xs', remValue: '0.75rem', pxValue: '12px' },
  { name: 'spacing-2xs', cssVar: '--spacing-2xs', remValue: '1rem', pxValue: '16px' },
  { name: 'spacing-xs', cssVar: '--spacing-xs', remValue: '1.25rem', pxValue: '20px' },
  { name: 'spacing-sm', cssVar: '--spacing-sm', remValue: '1.5rem', pxValue: '24px' },
  { name: 'spacing-md', cssVar: '--spacing-md', remValue: '2rem', pxValue: '32px' },
  { name: 'spacing-lg', cssVar: '--spacing-lg', remValue: '2.5rem', pxValue: '40px' },
  { name: 'spacing-xl', cssVar: '--spacing-xl', remValue: '3rem', pxValue: '48px' },
  { name: 'spacing-2xl', cssVar: '--spacing-2xl', remValue: '4rem', pxValue: '64px' },
  { name: 'spacing-3xl', cssVar: '--spacing-3xl', remValue: '5rem', pxValue: '80px' },
  { name: 'spacing-4xl', cssVar: '--spacing-4xl', remValue: '6rem', pxValue: '96px' },
  { name: 'spacing-5xl', cssVar: '--spacing-5xl', remValue: '8rem', pxValue: '128px' },
];
