// Generated by scripts/generate-tokens.mjs — do not edit by hand

export type TypographyToken = {
  name: string;
  cssVar: string;
  value: string;
};

export const fontFamilies: TypographyToken[] = [
  { name: 'primary',   cssVar: '--font-family-primary',   value: "Zilla Slab, Georgia, serif" },
  { name: 'secondary', cssVar: '--font-family-secondary', value: "Outfit, system-ui, sans-serif" },
  { name: 'mono',      cssVar: '--font-family-mono',      value: "JetBrains Mono, ui-monospace, monospace" },
];

export const fontSizes: TypographyToken[] = [
  { name: '2xl', cssVar: '--font-size-2xl', value: '1.5rem / 24px' },
  { name: '3xl', cssVar: '--font-size-3xl', value: '1.875rem / 30px' },
  { name: '4xl', cssVar: '--font-size-4xl', value: '2.25rem / 36px' },
  { name: '5xl', cssVar: '--font-size-5xl', value: '3rem / 48px' },
  { name: '6xl', cssVar: '--font-size-6xl', value: '3.75rem / 60px' },
  { name: '7xl', cssVar: '--font-size-7xl', value: '4.5rem / 72px' },
  { name: '8xl', cssVar: '--font-size-8xl', value: '6rem / 96px' },
  { name: '9xl', cssVar: '--font-size-9xl', value: '8rem / 128px' },
  { name: 'base', cssVar: '--font-size-base', value: '1rem / 16px' },
  { name: 'lg', cssVar: '--font-size-lg', value: '1.125rem / 18px' },
  { name: 'sm', cssVar: '--font-size-sm', value: '0.875rem / 14px' },
  { name: 'xl', cssVar: '--font-size-xl', value: '1.25rem / 20px' },
  { name: 'xs', cssVar: '--font-size-xs', value: '0.75rem / 12px' },
];

export const lineHeights: TypographyToken[] = [
  { name: '2xl', cssVar: '--line-height-2xl', value: '2rem / 32px' },
  { name: '3xl', cssVar: '--line-height-3xl', value: '2.25rem / 36px' },
  { name: '4xl', cssVar: '--line-height-4xl', value: '2.5rem / 40px' },
  { name: '5xl', cssVar: '--line-height-5xl', value: '4.5rem / 72px' },
  { name: '6xl', cssVar: '--line-height-6xl', value: '6.25rem / 100px' },
  { name: '7xl', cssVar: '--line-height-7xl', value: '1 (auto)' },
  { name: '8xl', cssVar: '--line-height-8xl', value: '1 (auto)' },
  { name: '9xl', cssVar: '--line-height-9xl', value: '1 (auto)' },
  { name: 'base', cssVar: '--line-height-base', value: '1.5rem / 24px' },
  { name: 'lg', cssVar: '--line-height-lg', value: '1.75rem / 28px' },
  { name: 'sm', cssVar: '--line-height-sm', value: '1.25rem / 20px' },
  { name: 'xl', cssVar: '--line-height-xl', value: '1.75rem / 28px' },
  { name: 'xs', cssVar: '--line-height-xs', value: '1rem / 16px' },
];

export const fontWeights: TypographyToken[] = [
  { name: 'thin',     cssVar: '--font-weight-thin',     value: '100' },
  { name: 'regular',  cssVar: '--font-weight-regular',  value: '400' },
  { name: 'semibold', cssVar: '--font-weight-semibold', value: '600' },
  { name: 'bold',     cssVar: '--font-weight-bold',     value: '700' },
];

export type TypeSpecimen = {
  name: string;
  label: string;
  className: string;
  sample: string;
};

export type TypeSpecimenGroup = {
  group: string;
  specimens: TypeSpecimen[];
};

export const typeSpecimenGroups: TypeSpecimenGroup[] = [
  {
    group: 'Displays',
    specimens: [
      {
        name: 'display-1',
        label: 'Display 1',
        className: 'font-serif [font-size:var(--font-size-6xl)] [font-weight:var(--font-weight-bold)] [line-height:var(--line-height-6xl)]',
        sample: 'The quick brown fox',
      },
      {
        name: 'display-2',
        label: 'Display 2',
        className: 'font-serif [font-size:var(--font-size-5xl)] [font-weight:var(--font-weight-bold)] [line-height:var(--line-height-5xl)]',
        sample: 'The quick brown fox',
      },
      {
        name: 'display-3',
        label: 'Display 3',
        className: 'font-serif [font-size:var(--font-size-4xl)] [font-weight:var(--font-weight-bold)] [line-height:var(--line-height-4xl)]',
        sample: 'The quick brown fox',
      },
    ],
  },
  {
    group: 'Headings',
    specimens: [
      {
        name: 'h1',
        label: 'H1',
        className: 'font-sans [font-size:var(--font-size-3xl)] [font-weight:var(--font-weight-bold)] [line-height:var(--line-height-3xl)]',
        sample: 'Design systems scale quality',
      },
      {
        name: 'h2',
        label: 'H2',
        className: 'font-sans [font-size:var(--font-size-2xl)] [font-weight:var(--font-weight-bold)] [line-height:var(--line-height-2xl)]',
        sample: 'Design systems scale quality',
      },
      {
        name: 'h3',
        label: 'H3',
        className: 'font-sans [font-size:var(--font-size-xl)] [font-weight:var(--font-weight-bold)] [line-height:var(--line-height-xl)]',
        sample: 'Tokens, Components, Patterns',
      },
      {
        name: 'h4',
        label: 'H4',
        className: 'font-sans [font-size:var(--font-size-lg)] [font-weight:var(--font-weight-bold)] [line-height:var(--line-height-lg)]',
        sample: 'Consistent, scalable UI',
      },
      {
        name: 'h5',
        label: 'H5',
        className: 'font-sans [font-size:var(--font-size-base)] [font-weight:var(--font-weight-bold)] [line-height:var(--line-height-base)]',
        sample: 'Consistent, scalable UI',
      },
    ],
  },
  {
    group: 'Body',
    specimens: [
      {
        name: 'body-lg',
        label: 'Body LG',
        className: 'font-sans [font-size:var(--font-size-lg)] [font-weight:var(--font-weight-regular)] [line-height:var(--line-height-lg)]',
        sample: 'The primary reading size. Used for paragraphs, descriptions, and most UI content.',
      },
      {
        name: 'body-base',
        label: 'Body Base',
        className: 'font-sans [font-size:var(--font-size-base)] [font-weight:var(--font-weight-regular)] [line-height:var(--line-height-base)]',
        sample: 'The primary reading size. Used for paragraphs, descriptions, and most UI content.',
      },
      {
        name: 'body-sm',
        label: 'Body SM',
        className: 'font-sans [font-size:var(--font-size-sm)] [font-weight:var(--font-weight-regular)] [line-height:var(--line-height-sm)]',
        sample: 'Secondary body text. Form labels, supporting descriptions, sidebar content.',
      },
    ],
  },
  {
    group: 'Captions',
    specimens: [
      {
        name: 'caption-1',
        label: 'Caption 1',
        className: 'font-sans [font-size:var(--font-size-base)] [font-weight:var(--font-weight-semibold)] [line-height:var(--line-height-sm)]',
        sample: 'Form label · UI label · Tag',
      },
      {
        name: 'caption-2',
        label: 'Caption 2',
        className: 'font-sans [font-size:var(--font-size-sm)] [font-weight:var(--font-weight-semibold)] [line-height:var(--line-height-sm)]',
        sample: 'Form label · UI label · Tag',
      },
      {
        name: 'caption-3',
        label: 'Caption 3',
        className: 'font-sans [font-size:var(--font-size-xs)] [font-weight:var(--font-weight-semibold)] [line-height:var(--line-height-xs)]',
        sample: 'Timestamp · Metadata · Fine print',
      },
    ],
  },
  {
    group: 'Code',
    specimens: [
      {
        name: 'code-1',
        label: 'Code 1',
        className: 'font-mono [font-size:var(--font-size-base)] [font-weight:var(--font-weight-regular)] [line-height:var(--line-height-base)]',
        sample: 'const greeting = "Hello, world!";',
      },
      {
        name: 'code-2',
        label: 'Code 2',
        className: 'font-mono [font-size:var(--font-size-sm)] [font-weight:var(--font-weight-regular)] [line-height:var(--line-height-sm)]',
        sample: 'const greeting = "Hello, world!";',
      },
    ],
  },
];
